# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# gcloud
# source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
# source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"

# Created by `pipx` on 2024-11-06 04:44:23
export PATH="$PATH:/Users/bhq/.local/bin"
