#!/usr/bin/env zsh
# directory navigation 
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias dot='cd ~/dotfiles'
alias tmp='cd /tmp'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias c='clear'
alias source='source ~/.zshrc'

# Git aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gl='git pull'
alias gp='git push'
alias gpl='git pull'
alias gpu='git push'
alias gpo='git push origin'

# eza with icons if installed
if command -v eza >/dev/null 2>&1; then
    alias e='eza --icons --group-directories-first'
    alias ea='eza --icons --group-directories-first -a'
    alias et='eza --icons --group-directories-first --tree'
    alias etr='eza --icons --group-directories-first --tree -R'
    alias etl='eza --icons --group-directories-first --tree -L 1'
    alias etll='eza --icons --group-directories-first --tree -L 2'
    alias etlll='eza --icons --group-directories-first --tree -L 3'
    alias el='eza --icons --group-directories-first --long'
    alias ela='eza --icons --group-directories-first --long -a'
    alias er='eza --icons --group-directories-first -s extension'
fi

alias ra='ranger'

alias h='zoxide'


# Brew aliases (only if brew is installed)
if command -v brew >/dev/null 2>&1; then
    alias bci='brew install --cask'
    alias bi='brew install'
    alias br='brew remove'
    alias bs='brew search'
    alias bi='brew info'
fi

alias ic='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs/'
# cd hnnh
